### ISSUE TITLE
文件添加、链接更换

### ISSUE THREAD

**Issue by DevHjz** [laoxong/CloudflareCustomPages#2]
大佬，我是Cloudflare-Chinese-Page的主人，最近**更新了一个翻译文件**、**代码地址有变动（换了用户名和新建了组织）**，麻烦更改下，谢谢！
新地址
https://github.com/STEAM-Lab/Cloudflare-Chinese-Page

**Comment by laoxong** [comment]
谢谢您的提醒,
已更新至您的新版本
